source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'DovMess_Example', :exclusive => true do
  pod "DovMess", :path => "../"
end

target 'DovMess_Tests', :exclusive => true do
  pod "DovMess", :path => "../"

  pod 'Specta'
  pod 'Expecta'
  pod 'OCMock'
end
